version: "3"
services:
  jupyter-spark:
    container_name: spark
    image: jupyter/pyspark-notebook
    ports:
      - 8888:8888
      - 4040:4040
      - 4041:4041
      - 4042:4042
      - 4043:4043
    volumes:
      - /home/doug/data-lake:/data/data-lake
      - /home/doug/notebooks:/home/jovyan
